BugTracker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls', namespace='user')),
    path('', include('main.urls', namespace='main')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

main/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import (ProjectListView,
                    projectLikeUnlike,
                    ProjectDetailTicketListView,
                    )

app_name = 'main'

urlpatterns = [
    path('projects/', ProjectListView.as_view(), name='project-list'),
    path('project-like-unlike/', projectLikeUnlike, name='project-like-unlike'),
    path('project-detail/', ProjectDetailTicketListView.as_view(),
         name='project-ticket-list')
]

user/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.urls import reverse_lazy
from django.contrib.auth import views as auth_views
from .views import (UserCreateView,
                    UserLogInView,
                    logout_view,
                    profileView,
                    avatar_delete,
                    )

app_name = 'user'

urlpatterns = [
    path('register/', UserCreateView.as_view(), name='register'),
    path('login/', UserLogInView.as_view(), name='login'),
    path('logout/', logout_view, name='logout'),
    path('profile/', profileView, name='profile'),
    path('avatar-delete/', avatar_delete, name='avatar-delete'),
    path('password-change/',
         auth_views.PasswordChangeView.as_view(
             template_name='registration/password_change.html',
             success_url=reverse_lazy('user:password_change_done')),
         name='password_change'),

    path('password-change/done/',
         auth_views.PasswordChangeDoneView.as_view(
             template_name='registration/password_change_done.html'),
         name='password_change_done'),

    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='registration/password_reset.html',
             success_url=reverse_lazy('user:password_reset_done')),
         name='password_reset'),

    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='registration/password_reset_done.html'),
         name='password_reset_done'),

    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='registration/password_reset_confirm.html',
             success_url=reverse_lazy('user:password_reset_complete')),
         name='password_reset_confirm'),

    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),
]

main/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth import get_user_model
from django.core.validators import FileExtensionValidator

import uuid


def user_deleted():
    return get_user_model().objects.get_or_create(username="deleted")[0]


class Project(models.Model):
    class Status(models.TextChoices):
        IN_PROGRESS = ('in_progress', _('IN PROGRESS'))
        STOPPED = ('stopped', _('STOPPED'))
        FINISH = ('finish', _('FINISH'))
    # uuid = models.UUIDField(
    #     _('UUID'),
    #     default=uuid.uuid4,
    #     editable=False,
    #     unique=True
    # )

    title = models.CharField(
        _('Title'),
        max_length=50,
    )
    description = models.TextField(
        _('Descriptions'),
        max_length=500
    )
    manager = models.ManyToManyField(
        get_user_model(),
        verbose_name=_('Manager'),
        related_name="is_manager_in",
        default=None,
        blank=True,
    )
    member = models.ManyToManyField(
        get_user_model(),
        verbose_name=_('Member'),
        related_name="is_member_in",
        default=None,
        blank=True,
    )
    status = models.CharField(
        _('Status'),
        max_length=20,
        choices=Status.choices,
        default=Status.IN_PROGRESS
    )
    liked = models.ManyToManyField(
        get_user_model(),
        verbose_name=_('Liked by'),
        related_name="liked",
        default=None,
        blank=True,
    )
    date_created = models.DateTimeField(
        _('Date created'),
        auto_now_add=True
    )
    latest = models.DateTimeField(
        _('Latest'),
        auto_now=True
    )

    def __str__(self):
        return f"{self.title}-{self.date_created}"

    def get_manager_name_set(self):
        name_set = []
        for manager in self.manager.all():
            name_set.append(manager.last_name)
            name_set.append(manager.first_name)
        name_set = set(name_set)
        name_set = ' '.join(name_set)
        return name_set

    class Meta:
        verbose_name = _('Project')
        verbose_name_plural = _('Projects')


class Ticket(models.Model):
    class Priority(models.TextChoices):
        GREEN = ('low', _('Low'))
        YELLOW = ('medium', _('Medium'))
        RED = ('high', _('High'))

    class Status(models.TextChoices):
        OPEN = ('open', _('Open'))
        ASSIGNED = ('assigned', _('Assigned'))
        CLOSED = ('closed', _('Closed'))

    class Type(models.TextChoices):
        BUGS_ERRORS = ('bugs_errors', _('Bugs/Errors'))
        FEATURE_REQUEST = ('feature_request', _('Feature Request'))
        QUESTIONS = ('questions', _('Questions'))

    project = models.ForeignKey(
        Project, on_delete=models.CASCADE,
        related_name="tickets",
        verbose_name=_('Project')
    )

    title = models.CharField(
        _('Title'),
        max_length=50
    )

    description = models.TextField(
        _('Description'),
        max_length=500,
    )

    submitter = models.ForeignKey(
        get_user_model(),
        on_delete=models.SET(user_deleted),
        related_name="is_submitter_of",
        verbose_name=_('Submitter')
    )

    priority = models.CharField(
        _('Priority'),
        choices=Priority.choices,
        max_length=20
    )

    status = models.CharField(
        _('Status'),
        choices=Status.choices,
        max_length=20,
        default=Status.OPEN
    )

    type = models.CharField(
        _('Type'),
        max_length=20,
        choices=Type.choices
    )

    assign_to = models.ForeignKey(
        get_user_model(),
        on_delete=models.SET(user_deleted),
        related_name="is_assigned_to",
        verbose_name=_('Assignment'),
    )

    date_created = models.DateTimeField(
        _('Date created'),
        auto_now_add=True
    )

    update = models.DateTimeField(
        _('Update'),
        auto_now=True,
    )

    def __str__(self):
        return f'{self.project.name}:{self.pk}'

    class Meta:
        verbose_name = _('Ticket')
        verbose_name_plural = _('Tickets')


class Comment(models.Model):
    ticket = models.ForeignKey(
        Ticket,
        on_delete=models.CASCADE,
        related_name="comments",
        verbose_name=_('Ticket')
    )
    body = models.TextField(
        _('Body'),
        blank=True,
        max_length=500,
    )
    date_created = models.DateTimeField(
        _('Date Created'),
        auto_now_add=True
    )
    last_edit = models.DateTimeField(
        _('Last Edit'),
        auto_now=True
    )


def get_image_path(instance, filename):
    return f'comments/{instance.comment.ticket.project.title}/\
        {instance.comment.ticket.id}/\
        {instance.comment.id}/{filename}'


class Attachment(models.Model):
    attach_to = models.ForeignKey(
        Comment,
        on_delete=models.CASCADE,
        related_name="attachments",
        verbose_name=_('Attach to')
    )
    attachment = models.ImageField(
        _('Attachment'),
        blank=True,
        null=True,
        validators=[
            FileExtensionValidator(['png', 'jpg', 'jpeg'])],
        upload_to=get_image_path
    )

main/views.py
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.shortcuts import render
from django.views.generic import (
    View,
    TemplateView
)
from django.contrib.auth import get_user_model
from django.db.models import Q, Count
from django.core.paginator import (
    EmptyPage,
    PageNotAnInteger,
    Paginator
)
from operator import attrgetter, or_, and_
from functools import reduce
from itertools import chain
from .models import (
    Project,
    Ticket,
    Comment,
    Attachment,
)
from django.http import JsonResponse


@method_decorator(login_required, name="dispatch")
class ProjectListView(TemplateView):
    template_name = 'main/projects.html'

    def get(self, request):
        num_ticketS = Count('tickets')
        liked_or_not = Count('liked',
                             filter=Q(liked__id__exact=request.user.id)
                             )
        qs = (Project.objects
              .annotate(num_tickets=num_ticketS)
              .annotate(liked_or_not=liked_or_not)
              )
        qs_json = list(qs.values())
        if request.is_ajax():
            return JsonResponse({data: qs_json}, safe=False)
        return render(request, 'main/projects.html', {'projects': qs})


@ login_required
def projectLikeUnlike(request):
    user = request.user
    if request.method == 'POST':
        project_id = request.POST.get('project_id')
        project = Project.objects.get(id=project_id)
        if user in project.liked.all():
            project.liked.remove(user)
        else:
            project.liked.add(user)
        return JsonResponse({"data": "success"}, safe=False)


class ProjectDetailTicketListView(View):
    def get(self, request):
        context = {}
        return render(request, 'main/project-detail.html', context)


class ProjectMemberManage(View):
    def get(self, request):
        pass

        # PROJECT_LIST_PER_PAGE = 2
        # def get_project_queryset(query=None):
        #     queryset = []
        #     queries = query.split(" ")
        #     for q in queries:
        #         posts = Project.objects.filter(
        #             Q(title__icontains=q) | Q(description__icontains=q)).distinct()
        #         for post in posts:
        #             queryset.append(post)
        #         # create unique set and then convert to list
        #         return list(set(queryset))

        # def projectListView(request):
        #     context = {}
        #     query = ""
        #     if request.method == 'GET':
        #         query = request.GET.get('q', '')
        #         context['query'] = str(query)

        #     project_list = sorted(get_project_queryset(
        #         query), key=attrgetter('date_created'), reverse=True)

        #     # Pagination
        #     page = request.GET.get('page', 1)
        #     project_list_paginator = Paginator(project_list, PROJECT_LIST_PER_PAGE)
        #     try:
        #         project_list = project_list_paginator.page(page)
        #     except PageNotAnInteger:
        #         project_list = project_list_paginator.page(PROJECT_LIST_PER_PAGE)
        #     except EmptyPage:
        #         project_list = project_list_paginator.page(
        #             project_list_paginator.num_pages)

        #     context['projects'] = project_list

        #     return render(request, "main/projects.html", context)
        #
        #
        # def projectDetailView(request, id):
        #     pass

main/templates/snippets/navbar.html
{% load static %}
{% load i18n %}
<!-- navbar -->
    <nav class="navbar navbar-expand-lg sticky-top nav-color m-0 p-1">
        <div class="container-fluid">
            <a class="navbar-brand d-none d-lg-inline-block ms-4" href="#">
                <img src="{% static 'main/bug.png' %}" alt="Brand" style="width: 35px; height:35px;">
                {% trans "Bug Tracker" %}
            </a>
            <!-- Navbar logo -->
            <a class="navbar-brand d-lg-none d-inline-block ms-2" href="#">
                <img src="{% static 'main/bug.png' %}" alt="Brand" style="width: 35px; height:35px;">
                {% trans "Bug Tracker" %}
            </a>
            <!-- Navbar logo -->
            <!-- Navbar Toggle -->
                <a class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggler"
                    aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
                    &#9776;
                </a>
            <!-- Navbar Toggle -->

            <div class="collapse navbar-collapse me-3" id="navbarToggler">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item ms-auto">
                        <a href="#" class="nav-link p-2">
                            <i class="bi bi-bell-fill" style="font-size:1.5rem;"></i>
                            <span class="badge bg-secondary">9</span>
                        </a>
                    </li>
                    <li class="nav-item ms-auto">
                        <a href="{% url 'user:password_change' %}" class="nav-link ms-3 p-2">{% trans "Change Password" %}</a>
                    </li>
                    {% comment %} <li class="nav-item">
                        <a href="#" class="nav-link m-2 menu-item">Blog</a>
                    </li> {% endcomment %}
                    <li class="nav-item ms-auto">
                        <a href="{% url 'user:logout' %}" class="nav-link ms-3 p-2">{% trans "Log Out" %}</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

main/templates/snippets/sidebar.html
{% load static %}
{% load i18n %}
<!-- Sidebar -->
    <nav id="sidebar">
        <!-- Sidebar close button -->
        <button type="button" id="close-side" onclick="closeSide()">
            <i class="fas fa-arrow-left"></i>
        </button>
        <!-- Sidebar close button -->

        <!-- Sidebar Open button-->
        <button type="button" class="border-0" id="open-side" onclick="openSide()">
            <i class="fas fa-arrow-right"></i>
        </button>
        <!-- Sidebar Open button-->

        <div class="sidebar-header text-center">
            <div class="img-container w-50 mx-auto">
                <a href="{% url 'user:profile' %}">
                    <img id="sidebar-avatar" src="{{ user.profile.image.url }}" alt="Profile Image">
                </a>
            </div>
            <div class="mt-3 mb-4">
                <h3>{% trans "Welcome, " %}<strong>{% trans user.username %}</strong></h3>
            </div>
        </div>

        <ul class="sidebar-nav">
            <li>
                <div class="dropdown">
                    <a href="#homeSubmenu" data-bs-toggle="collapse" aria-expanded="false"
                        aria-controls="homeSubmenu" class="dropdown-toggle">{% trans "Dashboard" %}</a>
                </div>
                    <ul class="collapse list-unstyled" id="homeSubmenu">
                        <li>
                            <a href="#">Home 1</a>
                        </li>
                        <li>
                            <a href="#">Home 2</a>
                        </li>
                        <li>
                            <a href="#">Home 3</a>
                        </li>
                    </ul>
            </li>
            <li id="projects">
                <a href="{% url 'main:project-list' %}" id="projects">{% trans "My Projects" %}</a>
            </li>
            <li>
                <div class="dropdown">
                    <a href="#pageSubmenu" data-bs-toggle="collapse" aria-expanded="false"
                        aria-controls="pageSubmenu" class="dropdown-toggle">My Tickets</a>
                </div>
                    <ul class="collapse list-unstyled" id="pageSubmenu">
                        <li>
                            <a href="#">Page 1</a>
                        </li>
                        <li>
                            <a href="#">Page 2</a>
                        </li>
                        <li>
                            <a href="#">Page 3</a>
                        </li>
                    </ul>
            </li>
            <li id="profile">
                <a href="{% url 'user:profile' %}">{% trans "Profile" %}</a>
            </li>
            <li>
                <a href="#">Contact</a>
            </li>
        </ul>
    </nav>
    <div id="overlay"></div>

<script>
    window.onresize = windowSizeCheck;
    const overlay = document.getElementById("overlay")
    const sidebar_open_btn = document.getElementById("open-side")
    overlay.addEventListener("click", e=>{
        closeSide()
    })
    function openSide() {
        var w = window.innerWidth;
        document.getElementById(
            "sidebar").style.marginLeft = "0px";
        document.getElementById(
            "content").style.marginLeft = "250px";
        document.getElementById(
            "open-side").style.display = "none";
        if (w <= 960) {
            document.getElementById(
            "overlay").classList.add("active");
            document.getElementById(
            "content").style.marginLeft = "0px";
        }
    }
    function closeSide() {
        document.getElementById(
            "sidebar").style.marginLeft = "-250px";
        document.getElementById(
            "content").style.marginLeft = "0px";
        document.getElementById(
            "open-side").style.display = "block";
        document.getElementById(
            "overlay").classList.remove("active");
    }
    function windowSizeCheck() {
        var w = window.innerWidth;
        var x = document.getElementById("sidebar");
        if (w <= 960 && x.style.marginLeft == "0px") {
            document.getElementById(
            "overlay").classList.add("active");
            document.getElementById(
            "content").style.marginLeft = "0px";
        }
    }
</script>