BugTracker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls', namespace='user')),
    path('', include('main.urls', namespace='main')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

main/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import (ProjectListView,
                    projectLikeUnlike,
                    ProjectDetailTicketListView,
                    )

app_name = 'main'

urlpatterns = [
    path('projects/', ProjectListView.as_view(), name='project-list'),
    path('project-like-unlike/', projectLikeUnlike, name='project-like-unlike'),
    path('project-detail/', ProjectDetailTicketListView.as_view(),
         name='project-ticket-list')
]

user/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.urls import reverse_lazy
from django.contrib.auth import views as auth_views
from .views import (UserCreateView,
                    UserLogInView,
                    logout_view,
                    profileView,
                    avatar_delete,
                    )

app_name = 'user'

urlpatterns = [
    path('register/', UserCreateView.as_view(), name='register'),
    path('login/', UserLogInView.as_view(), name='login'),
    path('logout/', logout_view, name='logout'),
    path('profile/', profileView, name='profile'),
    path('avatar-delete/', avatar_delete, name='avatar-delete'),
    path('password-change/',
         auth_views.PasswordChangeView.as_view(
             template_name='registration/password_change.html',
             success_url=reverse_lazy('user:password_change_done')),
         name='password_change'),

    path('password-change/done/',
         auth_views.PasswordChangeDoneView.as_view(
             template_name='registration/password_change_done.html'),
         name='password_change_done'),

    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='registration/password_reset.html',
             success_url=reverse_lazy('user:password_reset_done')),
         name='password_reset'),

    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='registration/password_reset_done.html'),
         name='password_reset_done'),

    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='registration/password_reset_confirm.html',
             success_url=reverse_lazy('user:password_reset_complete')),
         name='password_reset_confirm'),

    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),
]

user/models.py
from django.db import models
from django.shortcuts import reverse
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import AbstractBaseUser
from django.utils import timezone
from .managers import CustomUserManager
from django.contrib.auth import get_user_model
from PIL import Image
from BugTracker.settings import MEDIA_URL
import os


class CustomUser(AbstractBaseUser):
    email = models.EmailField(_('Email Address'), unique=True)
    username = models.CharField(_('Username'), max_length=20, unique=True)
    first_name = models.CharField(_('First Name'), max_length=20)
    last_name = models.CharField(_('Last Name'), max_length=20)
    is_active = models.BooleanField(_('is_active'), default=True)
    is_staff = models.BooleanField(_('is_staff'), default=False)
    is_superuser = models.BooleanField(_('is_superuser'), default=False)
    date_joined = models.DateTimeField(_('Date Joined'), auto_now_add=True)
    last_login = models.DateTimeField(_('Last Login'), auto_now=True)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email', 'first_name', 'last_name']

    objects = CustomUserManager()

    def get_absolute_url(self):
        return reverse('user.views.ProfileView', args=[str(self.username)])

    def get_full_name(self):
        """
        # Returns the first_name plus the last_name, with a space in between.
        """
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        "    Returns the short name for the user."
        return self.username

    def nature_key(self):
        return self.username

    def has_perm(self, perm, obj=None):
        return self.is_superuser

    def has_module_perms(self, app_label):
        return self.is_superuser

    def __str__(self):
        return self.username

    class Meta:
        verbose_name = _('The user')
        verbose_name_plural = _('Users')


def get_profile_image_path(instance, filename):
    return f'profile_pics/{instance.user.id}/{filename}'


class Profile(models.Model):
    user = models.OneToOneField(
        get_user_model(),
        on_delete=models.CASCADE
    )
    image = models.ImageField(
        default='default.png',
        upload_to=get_profile_image_path
    )

    def __str__(self):
        return f"{self.user.username}'s Profile"

    @property
    def get_absolute_image_url(self):
        return os.path.join(MEDIA_URL, self.image.url)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if self.image.name == 'default.jpg':
            return

        # def make_square(im, fill_color=(0, 0, 0, 0)):
        #     x, y = im.size
        #     size = max(x, y, 256)
        #     if x != y:
        #         new_im = Image.new('RGBA', (size, size), fill_color)
        #         new_im.paste(im, (int((size - x) / 2), int((size - y) / 2)))
        #         return new_im
        #     return im
        img = Image.open(self.image.path)
        # img = make_square(img)
        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            try:
                img.save(self.image.path)
            except:
                img = img.convert("RGB")
                img.save(self.image.path)

    class Meta:
        verbose_name = _('Profile')
        verbose_name_plural = _('User Profiles')

user/forms.py
from django import forms
from django.shortcuts import redirect
from django.db.models import Q
# from .models import CustomUser 用下面的方法取得User模型
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
from .models import Profile


class UserRegisterForm(forms.ModelForm):
    password1 = forms.CharField(
        label=_('Password'),
        required=True,
        help_text="Must be at least 8 characters long and can't be entirely numeric",
        widget=forms.PasswordInput
    )
    password2 = forms.CharField(
        label=_('Verify Password'),
        required=True,
        widget=forms.PasswordInput
    )

    def clean_password2(self):
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']
        if password1 != password2:
            raise ValidationError(message=_('Password must be the same as above.'),
                                  code='notmatch')
        return password2

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user
    # def is_valid(self):
    #     result = super().is_valid()
    #     # loop on *all* fields if key '__all__' found else only on errors:
    #     for x in (self.fields if '__all__' in self.errors else self.errors):
    #         attrs = self.fields[x].widget.attrs
    #         attrs.update({'class': attrs.get('class', '') + ' is-invalid',
    #                       'value': '{{ field.value }}'})
    #     return result

    class Meta:
        model = get_user_model()

        fields = ('first_name', 'last_name', 'username', 'email',)
        labels = {
            'email': _('Email address'),
            'first_name': _('First name'),
            'last_name': _('Last name')
        }

        error_messages = {
            'username': {
                'unique': _("Username has been used.")
            },
            'email': {
                'unique': _('Email has been used.')
            },
        }


class UserLoginForm(forms.Form):
    username = forms.CharField(label=_('Username'), required=True)
    password = forms.CharField(label=_('Password'), required=True)

    def clean(self):
        cleaned_data = super().clean()
        user_model = get_user_model()
        username = cleaned_data['username']
        password = cleaned_data['password']
        user = user_model.objects.filter(Q(username__iexact=username)).first()
        '''
        用user.check_password(password)來驗證password，不能用model，model中的password是亂碼
        '''
        mismatch = bool(user and not user.check_password(password))
        invalid = bool(not user)
        if mismatch:
            error = ValidationError(message="Username and password don't match !",
                                    code='mismatch')
            self.add_error('password', error)
            self.add_error('username', error)

        if invalid:
            error = ValidationError(message="Invalid username!",
                                    code='invalid')
            self.add_error('username', error)
        return cleaned_data


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ('username', 'first_name', 'last_name', 'email')
        labels = {
            'email': _('Email Address'),
            'first_name': _('First Name'),
            'last_name': _('Last Name'),
        }
        error_messages = {
            'username': {
                'unique': _("Username has been used.")
            },
        }


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('image',)

user/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin

from django.contrib.auth import login, authenticate, logout
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.decorators import login_required
from django.views.generic import (
    CreateView,
    FormView
)
from .models import CustomUser, Profile
from .forms import (
    UserRegisterForm,
    UserLoginForm,
    UserUpdateForm,
    ProfileUpdateForm
)


class UserCreateView(SuccessMessageMixin, CreateView):
    model = CustomUser
    form_class = UserRegisterForm
    template_name = 'user/register.html'
    success_url = '/login/'
    success_message = _("User Created !")


class UserLogInView(FormView):
    form_class = UserLoginForm
    template_name = 'user/login.html'
    success_url = '/profile/'

    def dispatch(self, request, *args, **kwargs):
        """
        Assign request to get method or post method, first method been called.
        """
        if request.user.is_authenticated:
            return redirect('user:profile')
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        """ process user login"""
        credentials = form.cleaned_data
        user = authenticate(username=credentials['username'],
                            password=credentials['password'])
        if user:
            login(self.request, user)
            messages.success(self.request, _(
                f"Hi {credentials['username']}. Welcome back !"))
            return super().form_valid(form)


@login_required
def logout_view(request):
    logout(request)
    return redirect('user:login')


@login_required
def profileView(request):
    user_data = (request.POST or None)
    profile_data = (request.FILES or None)
    u_form = UserUpdateForm(user_data, instance=request.user)
    p_form = ProfileUpdateForm(
        user_data, profile_data, instance=request.user.profile)

    if request.is_ajax():
        if p_form.is_valid():
            p_form.save()

    if u_form.is_valid():
        u_form.save()
        messages.success(request, _('Your account has been updated !'))
        return redirect('user:profile')
    context = {
        'u_form': u_form,
        'p_form': p_form
    }
    return render(request, 'user/profile.html', context)


@login_required
def avatar_delete(request):
    if request.is_ajax():
        data = {}
        user = request.user
        obj = Profile.objects.filter(user=user)[0]
        obj.image = 'default.png'
        obj.save(update_fields=['image'])
        data["status"] = "Avatar has been deleted !"
        data["default_image_url"] = obj.get_absolute_image_url
        return JsonResponse(data, safe=False)

user/templates/user/base.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block main %}
  <main role="main" class="container-fluid p-2 h-100">
    {% include 'snippets/messages.html' %}
      <div class="row h-100 m-0">
        {% block content %}{% endblock content %}
      </div>
  </main>
{% endblock main %}
{% block javascripts %}
{% endblock javascripts %}

user/templates/user/login.html
{% extends 'user/base.html' %}
{% load static %}
{% load i18n %}
{% block content %}
<div class="col-12 col-sm-8 offset-sm-2 col-md-6 offset-md-3 form-card">
    <form method="POST" class="row row-no-gutters">
        {% csrf_token %}
        <div class="col-12 form-card-brand">
            <legend class="brand-title pb-2 mb-1 text-center">
                {% translate 'LOG IN' %}</legend>
        </div>
        {% for field in form %}
            <div class="col-12 mt-3">
                <div class="form-floating">
                    <input {% if field.name == 'password'%} type="password" {% else %} type="text" {% endif %}
                        name="{{ field.name }}"
                        class="form-control form-input position-relative {% if field.errors %}is-invalid{% endif %}"
                        placeholder="Enter {{ field.label }}"
                        id="{{ field.id_for_label }}" required>
                        {% if field.name == 'password' %}
                            <i class="fas fa-eye-slash togglePassword" id="{{ field.name }}" onclick="togglePassword(this)"></i>
                            <a class="link-bl form-input-btm-text" href="{% url 'user:password_reset' %}">Forget password ?</a>
                        {% endif %}
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                </div>
                <!-- 這裡的error_message要用 |striptags，才能取得錯誤訊息 -->
                {% if form.errors %}
                    {% for error_message in field.errors %}
                        <p class="invalid-feedback d-block"> <strong>{{ error_message|striptags }}</strong></p>
                    {% endfor %}
                {% endif %}
            </div>
        {% endfor %}
        <div class="form-check col-12 ms-3 mt-2">
            <input type="checkbox" class="form-check-input" id="dropdownCheck2">
            <label class="form-check-label" for="dropdownCheck2">
                Remember me
            </label>
        </div>
        <div class="col-12 text-center form-group mt-3 pb-3">
            <button class="btn btn-lg custom-btn" type="submit">Sign In</button>
        </div>
    </form>
    <div class="border-top pt-1 text-center">
        <small class="text-muted">
            Don't have an account? <a class="link-bl ml-2" href="{% url 'user:register'%}">Sign Up</a>
        </small>
    </div>
</div>
{% endblock content %}
{% block javascripts %}
<script type="text/javascript">
    function togglePassword(element){
        var password_field = element.previousElementSibling;
        const type = password_field.getAttribute('type') === 'password' ? 'text' : 'password';
        password_field.setAttribute('type', type);
        element.classList.toggle('fa-eye-slash');
        element.classList.toggle('fa-eye');
    }
</script>
{% endblock javascripts %}

user/templates/user/login_form.html
{% extends 'user/user_base.html' %}
{% load static %}
{% load i18n %}
{% block content %}
<div class="col-12 col-sm-8 offset-sm-2 col-md-6 offset-md-3 form-card">
    <form method="POST" class="row row-no-gutters">
        {% csrf_token %}
        <div class="col-12 form-card-brand">
            <legend class="brand-title pb-2 mb-1 text-center">
                {% translate 'LOG IN' %}</legend>
        </div>
        {% for field in form %}
            {% if field.name == 'password' %}
            <div class="col-12 form-group pb-3">
            {% else %}
            <div class="col-12 form-group pb-3">
            {% endif %}
            {{ field.label_tag }}
            <div class="password-field">
                <input {% if field.name == 'password'%} type="password" {% else %} type="text" {% endif %}
                    name="{{ field.name }}" class="textinput textInput form-control form-input" placeholder="Enter {{ field.label }}"
                    id="id_{{ field.name }}" required>
                    {% if field.name == 'password' %}
                        <i class="fas fa-eye-slash togglePassword" id="{{ field.name }}" onclick="togglePassword(this)"></i>
                        <a class="link-bl form-input-text" href="#">Forget password ?</a>
                    {% endif %}
            </div>
            <!-- 這裡的error_message要用 |striptags，才能取得錯誤訊息 -->
            {% if form.errors %}
                {% for error_message in field.errors %}
                    <p class="invalid-feedback d-block"> <strong>{{ error_message|striptags }}</strong></p>
                {% endfor %}
            {% endif %}
            </div>
        {% endfor %}
        <div class="form-check col-12 ms-3">
            <input type="checkbox" class="form-check-input" id="dropdownCheck2">
            <label class="form-check-label" for="dropdownCheck2">
                Remember me
            </label>
        </div>
        <div class="col-12 text-center form-group mt-3 pb-3">
            <button class="btn btn-lg custom-btn" type="submit">Sign In</button>
        </div>
    </form>
    <div class="border-top pt-1 text-center">
        <small class="text-muted">
            Don't have an account? <a class="link-bl ml-2" href="{% url 'register'%}">Sign Up</a>
        </small>
    </div>
</div>

<script type="text/javascript">
    function togglePassword(element){
        var password_field = document.getElementById('id_password');
        const type = password_field.getAttribute('type') === 'password' ? 'text' : 'password';
        password_field.setAttribute('type', type);
        element.classList.toggle('fa-eye-slash');
        element.classList.toggle('fa-eye');
    }
</script>
{% endblock content %}

user/templates/user/register.html
{% extends 'user/base.html' %}
{% load static %}
{% load i18n %}
{% block content %}
<div class="col-12 col-sm-8 offset-sm-2 col-md-6 offset-md-3 form-card">
    <form method="POST" class="row">
        {% csrf_token %}
        <div class="col-12 form-card-brand mb-4">
            <legend class="brand-title text-center">
                {% trans "Bug Tracker" %}
                <img src="{% static 'main/bug.png' %}" alt="Brand">
            </legend>
        </div>
        {% for field in form %}
            {% if field.name == 'password1' or field.name == 'password2' %}
                <div class="col-12 pb-3">
            {% elif field.name == 'first_name' or field.name == 'last_name' %}
                <div class="col-6 pb-3">
            {% else %}
                <div class="col-12 pb-3">
            {% endif %}
                <div class="form-floating">
                    <input
                        {% if field.name == 'email' %}
                            type="email"
                        {% elif field.name == 'password1' or field.name == 'password2' %}
                            type="password"
                        {% else %}
                            type="text"
                        {% endif %}
                        name="{{ field.name }}"
                        {% if field.name != 'password2' %} placeholder="{{ field.label|escape }}"
                        {% else %} placeholder="Enter Password Again" {% endif %}
                        {% if field.value and field.name != 'password1' and field.name != 'password2' %}
                            value="{{ field.value }}"
                        {% endif %}
                        class="form-control form-input {% if field.errors %}is-invalid{% endif %}"
                        id="{{ field.id_for_label }}" required>
                    {% if field.name == 'password1' or field.name == 'password2' %}
                    <i class="fas fa-eye-slash togglePassword" id="{{ field.name }}" onclick="togglePassword(this)"></i>
                    {% endif %}
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                </div>
                {% if form.errors %}
                    {% for error_message in field.errors %}
                <!--這裡的error_message要用 |striptags，才能取得錯誤訊息-->
                <!--invalid-feedback後面要加d-block才會強制顯示錯誤訊息，否則有可能不會顯示-->
                    <p class="invalid-feedback d-block"><strong>{{ error_message|striptags }}</strong></p>
                    {% endfor %}
                {% endif %}
            </div>
        {% endfor %}
        <div class="col-12 text-center form-group mb-3">
            <button class="btn btn-lg custom-btn" type="submit">Sign Up</button>
        </div>
    </form>
    <div class="border-top pt-1 text-center">
        <small class="text-muted">
            Already Have An Account? <a class="link-bl ml-2" href="{% url 'user:login' %}">Sign In</a>
        </small>
    </div>
</div>
{% endblock content %}
{% block javascripts %}
<script type="text/javascript">
    function togglePassword(element){
        var password_field = element.previousElementSibling;
        const type = password_field.getAttribute('type') === 'password' ? 'text' : 'password';
        password_field.setAttribute('type', type);
        element.classList.toggle('fa-eye-slash');
        element.classList.toggle('fa-eye');
    }
</script>
{% endblock javascripts %}

user/templates/user/register_form.html
{% extends 'user/user_base.html' %}
{% load static %}
{% load i18n %}
{% block content %}
<div class="col-12 col-sm-8 offset-sm-2 col-md-6 offset-md-3 form-card">
    <form method="POST" class="row">
        {% csrf_token %}
        <div class="col-12 form-card-brand">
            <legend class="brand-title mb-2 text-center">
                {% trans "Bug Tracker" %}
                <img src="{% static 'main/bug.png' %}" alt="Brand"></legend>
        </div>
        {% for field in form %}
            {% if field.name == 'password1' or field.name == 'password2' %}
                <div class="col-12 form-group password-form pb-3">
            {% elif field.name == 'first_name' or field.name == 'last_name' %}
                <div class="col-6 form-group pb-3">
            {% else %}
                <div class="col-12 form-group pb-3">
            {% endif %}
                {{ field.label_tag }}
                <div class="password-field">
                    <input
                        {% if field.name == 'email' %}
                            type="email"
                        {% elif field.name == 'password1' or field.name == 'password2' %}
                            type="password"
                        {% else %}
                            type="text"
                        {% endif %}
                        name="{{ field.name }}"
                        {% if field.name != 'password2' %} placeholder="{{ field.label|escape }}"
                        {% else %} placeholder="Enter Password Again" {% endif %}
                        {% if field.value and field.name != 'password1' and field.name != 'password2' %}
                            value="{{ field.value }}"
                        {% endif %}
                        class="textinput textInput form-control form-input {% if field.errors %}invalid{% endif %}"
                        id="id_{{ field.name }}" required>
                        {% if field.name == 'password1' or field.name == 'password2' %}
                        <i class="fas fa-eye-slash togglePassword" id="{{ field.name }}" onclick="togglePassword(this)"></i>
                        {% endif %}
                </div>
                {% if form.errors %}
                    {% for error_message in field.errors %}
                <!--這裡的error_message要用 |striptags，才能取得錯誤訊息-->
                <!--invalid-feedback後面要加d-block才會強制顯示錯誤訊息，否則有可能不會顯示-->
                    <p class="invalid-feedback d-block"><strong>{{ error_message|striptags }}</strong></p>
                    {% endfor %}
                {% endif %}
            </div>
        {% endfor %}
        <div class="col-12 text-center form-group mb-3">
            <button class="btn btn-lg custom-btn" type="submit">Sign Up</button>
        </div>
    </form>
    <div class="border-top pt-1 text-center">
        <small class="text-muted">
            Already Have An Account? <a class="link-bl ml-2" href="{% url 'login' %}">Sign In</a>
        </small>
    </div>
</div>

<script type="text/javascript">
    function togglePassword(element){
        var password_field_1 = document.getElementById('id_password1');
        var password_field_2 = document.getElementById('id_password2');
        if (element.id === "password1"){
            let type_a = password_field_1.getAttribute('type') === 'password' ? 'text' : 'password';
            password_field_1.setAttribute('type', type_a);
        }else{
            let type_b = password_field_2.getAttribute('type') === 'password' ? 'text' : 'password';
            password_field_2.setAttribute('type', type_b);
        }
        element.classList.toggle('fa-eye-slash');
        element.classList.toggle('fa-eye');
    }
</script>
{% endblock %}